### ISSUE TITLE
Build fail on Linux 6.12.* aarch64: /var/lib/dkms/sharp-drm/1.5/build/src/drm_iface.c:36:10: fatal error: drm/drm_fbdev_generic.h: No such file or directory

### ISSUE THREAD

**Issue by hawkin69** [ardangelo/sharp-drm-driver#14]
Hello,

sharp-drm-driver builds successfully on 6.6.1 aarch64 (which comes with raspbian / debian bookworm). When I run `apt upgrade`, linux-6.12.20 will be pulled and an attempt will be made to recompile shap-drm. This build attempt fails with:

```
/var/lib/dkms/sharp-drm/1.5/build/src/drm_iface.c:36:10: fatal error: drm/drm_fbdev_generic.h: No such file or directory
   36 | #include <drm/drm_fbdev_generic.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
```

The above error rings similar to https://github.com/ardangelo/sharp-drm-driver/issues/11.

More details:
```
$ uname -a
Linux beep 6.12.20+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.12.20-1+rpt1~bpo12+1 (2025-03-19) aarch64 GNU/Linux
```

Apt install failure:
```
$ sudo apt install sharp-drm

[...]

Building module:
Cleaning build area...
make -j4 KERNELRELEASE=6.12.20+rpt-rpi-v8 && make -C /var/lib/dkms/sharp-drm/1.5/source install_aux BUILD_DIR=/var/lib/dkms/sharp-drm/1.5/build................
.......(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.12.20+rpt-rpi-v8 (aarch64)
Consult /var/lib/dkms/sharp-drm/1.5/build/make.log for more information.
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
dkms: autoinstall for kernel: 6.12.20+rpt-rpi-v8 failed!
run-parts: /etc/kernel/postinst.d/dkms exited with return code 11
dpkg: error processing package linux-image-6.12.20+rpt-rpi-v8 (--configure):
 installed linux-image-6.12.20+rpt-rpi-v8 package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of linux-headers-6.12.20+rpt-rpi-2712:
 linux-headers-6.12.20+rpt-rpi-2712 depends on linux-image-6.12.20+rpt-rpi-2712 (= 1:6.12.20-1+rpt1~bpo12+1) | linux-image-6.12.20+rpt-rpi-2712-unsigned (= 1:6
.12.20-1+rpt1~bpo12+1); however:
  Package linux-image-6.12.20+rpt-rpi-2712 is not configured yet.
  Package linux-image-6.12.20+rpt-rpi-2712-unsigned is not installed.
[...]
```

/var/lib/dkms/sharp-drm/1.5/build/make.log:
```
DKMS make.log for sharp-drm-1.5 for kernel 6.12.20+rpt-rpi-v8 (aarch64)
Mon 21 Apr 23:00:51 EDT 2025
dtc -@ -I dts -O dtb -W no-unit_address_vs_reg -o sharp-drm.dtbo sharp-drm.dts
make -C '/lib/modules/6.12.20+rpt-rpi-v8/build' M='/var/lib/dkms/sharp-drm/1.5/build'
make[1]: Entering directory '/usr/src/linux-headers-6.12.20+rpt-rpi-v8'
  CC [M]  /var/lib/dkms/sharp-drm/1.5/build/src/main.o
  CC [M]  /var/lib/dkms/sharp-drm/1.5/build/src/drm_iface.o
  CC [M]  /var/lib/dkms/sharp-drm/1.5/build/src/params_iface.o
  CC [M]  /var/lib/dkms/sharp-drm/1.5/build/src/ioctl_iface.o
In file included from /usr/src/linux-headers-6.12.20+rpt-common-rpi/include/linux/kernel.h:31,
                 from /usr/src/linux-headers-6.12.20+rpt-common-rpi/include/linux/cpumask.h:11,
                 from /usr/src/linux-headers-6.12.20+rpt-common-rpi/include/linux/smp.h:13,
                 from /usr/src/linux-headers-6.12.20+rpt-common-rpi/include/linux/lockdep.h:14,
                 from /usr/src/linux-headers-6.12.20+rpt-common-rpi/include/linux/mutex.h:17,
                 from /usr/src/linux-headers-6.12.20+rpt-common-rpi/include/linux/kernfs.h:11,
                 from /usr/src/linux-headers-6.12.20+rpt-common-rpi/include/linux/sysfs.h:16,
                 from /usr/src/linux-headers-6.12.20+rpt-common-rpi/include/linux/kobject.h:20,
                 from /usr/src/linux-headers-6.12.20+rpt-common-rpi/include/linux/cdev.h:5,
                 from /var/lib/dkms/sharp-drm/1.5/build/src/ioctl_iface.c:3:
/var/lib/dkms/sharp-drm/1.5/build/src/ioctl_iface.c: In function ‘sharp_memory_ioctl_ov_add’:
/usr/src/linux-headers-6.12.20+rpt-common-rpi/include/linux/kern_levels.h:5:25: warning: format ‘%zu’ expects argument of type ‘size_t’, but argument 3 has typ
e ‘int’ [-Wformat=]
    5 | #define KERN_SOH        "\001"          /* ASCII Start Of Header */
      |                         ^~~~~~
/usr/src/linux-headers-6.12.20+rpt-common-rpi/include/linux/printk.h:462:25: note: in definition of macro ‘printk_index_wrap’
  462 |                 _p_func(_fmt, ##__VA_ARGS__);                           \
      |                         ^~~~
/var/lib/dkms/sharp-drm/1.5/build/src/ioctl_iface.c:39:17: note: in expansion of macro ‘printk’
   39 |                 printk(KERN_ERR "sharp_drm: failed to copy overlay buffer from userspace (could not copy %zu/%zu)\n",
      |                 ^~~~~~
/usr/src/linux-headers-6.12.20+rpt-common-rpi/include/linux/kern_levels.h:11:25: note: in expansion of macro ‘KERN_SOH’
   11 | #define KERN_ERR        KERN_SOH "3"    /* error conditions */
      |                         ^~~~~~~~
/var/lib/dkms/sharp-drm/1.5/build/src/ioctl_iface.c:39:24: note: in expansion of macro ‘KERN_ERR’
   39 |                 printk(KERN_ERR "sharp_drm: failed to copy overlay buffer from userspace (could not copy %zu/%zu)\n",
      |                        ^~~~~~~~
/var/lib/dkms/sharp-drm/1.5/build/src/main.c:67:6: warning: no previous prototype for ‘sharp_memory_set_invert’ [-Wmissing-prototypes]
   67 | void sharp_memory_set_invert(int setting)
      |      ^~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/sharp-drm/1.5/build/src/main.c:73:7: warning: no previous prototype for ‘sharp_memory_add_overlay’ [-Wmissing-prototypes]
   73 | void* sharp_memory_add_overlay(int x, int y, int width, int height,
      |       ^~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/sharp-drm/1.5/build/src/main.c:80:6: warning: no previous prototype for ‘sharp_memory_remove_overlay’ [-Wmissing-prototypes]
   80 | void sharp_memory_remove_overlay(void* entry)
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/sharp-drm/1.5/build/src/main.c:86:7: warning: no previous prototype for ‘sharp_memory_show_overlay’ [-Wmissing-prototypes]
   86 | void* sharp_memory_show_overlay(void* storage)
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/sharp-drm/1.5/build/src/main.c:92:6: warning: no previous prototype for ‘sharp_memory_hide_overlay’ [-Wmissing-prototypes]
   92 | void sharp_memory_hide_overlay(void* display)
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/sharp-drm/1.5/build/src/main.c:98:6: warning: no previous prototype for ‘sharp_memory_clear_overlays’ [-Wmissing-prototypes]
   98 | void sharp_memory_clear_overlays(void)
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/sharp-drm/1.5/build/src/drm_iface.c:36:10: fatal error: drm/drm_fbdev_generic.h: No such file or directory
   36 | #include <drm/drm_fbdev_generic.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/src/linux-headers-6.12.20+rpt-common-rpi/scripts/Makefile.build:249: /var/lib/dkms/sharp-drm/1.5/build/src/drm_iface.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/usr/src/linux-headers-6.12.20+rpt-common-rpi/Makefile:1969: /var/lib/dkms/sharp-drm/1.5/build] Error 2
make[1]: *** [/usr/src/linux-headers-6.12.20+rpt-common-rpi/Makefile:236: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.12.20+rpt-rpi-v8'
make: *** [Makefile:43: all] Error 2
```

Thanks and cheers
